// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('./play-area/p/bazzzzzzzzzzzzzzz.js', ['foo.Bar'], ['foo.Baz']);
goog.addDependency('./play-area/p/lib/bar.js', ['foo.Baz'], []);
